MODEL:
  ANCHOR_GENERATOR:
    SIZES: [[32], [64], [128], [256]]  # One size for each in feature map
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]  # Three aspect ratios (same for all in feature maps)
  PROPOSAL_GENERATOR:
    NAME: "RPNCustom"
  RPN:
    HEAD_NAME: "RPNHeadCustom"
    IN_FEATURES: ["P_4", "P_8", "P_16", "P_32"]
    PRE_NMS_TOPK_TRAIN: 2000  # Per FPN level
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
    # Detectron1 uses 2000 proposals per-batch,
    # (See "modeling/rpn/rpn_outputs.py" for details of this legacy issue)
    # which is approximately 1000 proposals per-image since the default batch size for FPN is 2.
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 1000
    SMOOTH_L1_BETA: 0.1111
    # IOU_THRESHOLDS: [0.3,0.7]
  ROI_HEADS:
    NAME: "CustomROIHeads"
    # BATCH_SIZE_PER_IMAGE: 256 # number of proposals to sample for training
    # POSITIVE_FRACTION: 0.25 # fraction of positive (foreground) proposals to sample for training.
    IN_FEATURES: ["P_4", "P_8", "P_16", "P_32"]
    NUM_CLASSES: 19
    # PROPOSAL_APPEND_GT: 
    # IOU_THRESHOLDS: [0.5]
    # IOU_LABELS: 
  ROI_BOX_HEAD:
    # POOLER_RESOLUTION: 14
    POOLER_TYPE: "ROIAlign" # "ROIAlignV2"
BATCH_SIZE: 1
NUM_CLASS: 19

EFFICIENTNET_ID: 5 # Id of the Efficient net model  (Not the usual use in detectron2)